services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

  backend1:
    build:
      context: ./server_files/backend1
    container_name: backend1
    networks:
      - app-network

  backend2:
    build:
      context: ./server_files/backend2
    container_name: backend2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge